#!/bin/bash
# tinc name is $NAME
# tinc server daemon to connect to
# tinc host import is SERVERIMPORT

echo "Hello from tincinit."
echo "environment variables:"
env

echo "-------------------------"
set -x

echo "NETNAME is $NETNAME"
echo "Initializing."
tinc -n $NETNAME init $NAME

echo "!!!!!!!!!!!!!!!!!!!!"

echo "Adding address."
tinc -n $NETNAME add address $EXTIP
tinc -n $NETNAME add port $EXTPORT
tinc -n $NETNAME add subnet $PRIVIP/32

if [ ! -z "$SERVERIMPORT" ]; then
  echo "!!!!!!!!!! Importing $NETNAME server data."
  tinc -n $NETNAME import <<< "$SERVERIMPORT"
  tinc -n $NETNAME add connectto server
fi

echo "Writing IP address to file."
echo $PRIVIP>/usr/local/etc/tinc/myipaddress

echo "Exporting data."
tinc -n $NETNAME export > /usr/local/exported.tinc

echo "Updating tinc-up."
mv /usr/local/etc/tinc-up /usr/local/etc/tinc/$NETNAME/

echo "Starting tinc daemon."
tincd -n $NETNAME

echo "FINISHED"

sleep infinity

