#!/bin/bash
# tinc name is $NAME
# tinc server daemon to connect to
# tinc host import is SERVERIMPORT

mkdir -p /dev/net
mknod -m 600 /dev/net/tun c 10 200
#chmod 600 /dev/net/tun

echo "Initializing."
tinc -n vpn init NAME

echo "Adding address."
tinc -n vpn add address vpn.$DOMAIN

if [ ! -z "$SERVERIMPORT" ]; then
  echo "Importing vpn server data."
  tinc -n vpn import <<< "$SERVERIMPORT"
  tinc -n vpn add connectto server
fi

echo "Writing IP address to file."
echo $PRIVIP>/usr/local/etc/tinc/myipaddress

echo "Exporting data."
tinc -n vpn export > /usr/local/exported.tinc

echo "Updating tinc-up."
mv /usr/local/etc/tinc-up /usr/local/etc/tinc/vpn/

echo "Starting tinc daemon."
tincd -D -n vpn

echo "Daemon exited."


